In [1]:
# Singular-value decomposition 
from numpy import array 
from scipy.linalg import svd 
from numpy import zeros 
from numpy import diag 
# Define a matrix 
A = array([[3, 2], [2, 3], [2, -2]]) 
print("[ 초기 행렬 ]") 
print(A)

[ 초기 행렬 ]
[[ 3  2]
 [ 2  3]
 [ 2 -2]]


In [2]:
# SVD calculation 
U, s, VT = svd(A) 
print("[ SVD 라이브러리 결과 ]") 
print(U) 
print(s) 
print(VT)

[ SVD 라이브러리 결과 ]
[[-7.07106781e-01  2.35702260e-01 -6.66666667e-01]
 [-7.07106781e-01 -2.35702260e-01  6.66666667e-01]
 [ 4.46197169e-17  9.42809042e-01  3.33333333e-01]]
[5. 3.]
[[-0.70710678 -0.70710678]
 [ 0.70710678 -0.70710678]]


In [6]:
# Populate Sigma with n x n diagonal matrix 
Sigma = zeros((A.shape[0], A.shape[1])) 
Sigma[:A.shape[0], :A.shape[0]] = diag(s) 
print("[ 행렬 형태의 Sigma 확인 ]") 
print(Sigma)

ValueError: could not broadcast input array from shape (2,2) into shape (3,2)